"""add opportunity_type and no_experience_required to jobs

Revision ID: 4a6f936200d1
Revises: 28701544f5e0
Create Date: 2026-09-02 13:27:08.275800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6f936200d1'
down_revision: Union[str, Sequence[str], None] = '28701544f5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('opportunity_type', sa.String(length=50), server_default='Job', nullable=False))
    op.add_column('jobs', sa.Column('no_experience_required', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_jobs_no_experience_required'), 'jobs', ['no_experience_required'], unique=False)
    op.create_index(op.f('ix_jobs_opportunity_type'), 'jobs', ['opportunity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_opportunity_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_no_experience_required'), table_name='jobs')
    op.drop_column('jobs', 'no_experience_required')
    op.drop_column('jobs', 'opportunity_type')
    # ### end Alembic commands ###
