"""add follow_up_date to applications

Revision ID: 9648858ae105
Revises: ec6e71e0ac7d
Create Date: 2026-04-19 14:44:53.544959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9648858ae105'
down_revision: Union[str, Sequence[str], None] = 'ec6e71e0ac7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('follow_up_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'follow_up_date')
    # ### end Alembic commands ###
